name: skore

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: "bash"

jobs:
  skore-test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.12"]
        scikit-learn: ["1.6"]
        include:
          - os: "ubuntu-latest"
            python: "3.12"
            scikit-learn: "1.6"
            coverage: true
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        id: setup-python
        with:
          python-version: ${{ matrix.python }}
          check-latest: True
          cache: pip

      - name: Restore python-venv
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: cache-python-venv
        with:
          path: 'skore/venv'
          key: >-
            python-venv
            -${{ matrix.os }}
            -${{ steps.setup-python.outputs.python-version }}
            -${{ hashFiles(format('ci/requirements/skore/python-{0}/scikit-learn-{1}/test-requirements.txt', matrix.python, matrix.scikit-learn)) }}

      - name: Setup python-venv
        working-directory: "skore/"
        run: |
          set -eu

          # Ensure venv is created
          python -m venv venv

          # Activate venv for each step depending on the OS
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
              echo "${GITHUB_WORKSPACE}/skore/venv/bin" >> ${GITHUB_PATH}
              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}/skore/venv" >> ${GITHUB_ENV}
          else
              echo "${GITHUB_WORKSPACE}\\skore\\venv\\Scripts" >> ${GITHUB_PATH}
              echo "VIRTUAL_ENV=${GITHUB_WORKSPACE}\\skore\\venv" >> ${GITHUB_ENV}
          fi

      - name: Install dependencies in python-venv
        working-directory: ${{ format('ci/requirements/skore/python-{0}/scikit-learn-{1}', matrix.python, matrix.scikit-learn) }}
        if: steps.cache-python-venv.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip build
          python -m pip install --requirement test-requirements.txt

      - name: Save python-venv
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: steps.cache-python-venv.outputs.cache-hit != 'true'
        with:
          path: 'skore/venv'
          key: ${{ steps.cache-python-venv.outputs.cache-primary-key }}

      - name: Build
        working-directory: skore/
        run: python -m build

      - name: Install
        working-directory: skore/dist/
        run: wheel=(*.whl); python -m pip install --force-reinstall --no-deps "${wheel}"

      - name: Show dependencies versions
        working-directory: skore/
        run: python -c 'import skore; skore.show_versions()'

      - name: Test without coverage
        if: ${{ ! matrix.coverage }}
        timeout-minutes: 10
        working-directory: skore/
        run: python -m pytest -n auto src/ tests/ --no-cov

      - name: Test with coverage
        if: ${{ matrix.coverage }}
        timeout-minutes: 10
        working-directory: skore/
        run: |
          mkdir coverage
          python -m pytest -n auto src/ tests/ --junitxml=coverage/coverage.xml --cov-config=pyproject.toml --cov | tee coverage/coverage.txt

      - name: Upload coverage reports
        if: ${{ matrix.coverage && (github.event_name == 'pull_request') }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: skore-coverage
          path: skore/coverage/

  skore:
    needs:
      - skore-test
    if: ${{ always() }}
    runs-on: Ubuntu-latest
    steps:
      - shell: bash
        run: |
          [[  ${{ contains(needs.*.result, 'failure') }} = false ]]
